name: QA

on: [ merge_group, push, pull_request ]

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S git typos

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run spellchecker
        run: typos
